name: sys-info-test
description: 'Get System OS Information'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@master
    - name: use npm
      run: |
       npm install
       npm start